name: deep_talks
description: "DeepTalks – Your private space for love & memories."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # Auth
  google_sign_in: ^6.3.0

  # Agora WebRTC
  agora_rtc_engine: ^6.5.0

  # Media
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  cloudinary_public: ^0.23.1
  swipe_to: ^1.0.6
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^20.1.0
  flutter_fortune_wheel: ^1.3.2
  flutter_card_swiper: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

