org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
android.enforceUniquePackageName=false
android.suppressUnsupportedCompileSdk=36
android.defaultConfig.vectorDrawables.useSupportLibrary=true
android.injected.build.model.only.versioned=3
android.overrideCheckVCS=true


android.newDsl=false
android.builtInKotlin=false

kotlin.code.style=official